### ISSUE TITLE
Endless loop on logout

### ISSUE THREAD

**Issue by Romick2005** [Kasheftin/nuxt-auth-from-scratch#2]
Hi have you try to use logout functionality, because I have some problems with that.
When I dispatching me.$store.dispatch("auth/reset") I ended up with endless loop inside auth midleware on line    
`return redirect("/login");`
Can you please give me any hints what the problem it could be?

**Comment by Kasheftin** [comment]
Hi, I've just tried it, and it works for me. Does the login action works as expected for you? It didn't worked for me, so I added cors middleware to the express and options request handler (usually nginx cares for these things, but for local dev I had to add it).

**Comment by Romick2005** [comment]
Yes it works. My bad in custom logic. Because all links should be accessible only for loggedIn User I change that to:
```
export default function ({store, redirect, route}) {
  const userIsLoggedIn = !!store.state.auth.user;
  const fullPath = route.fullPath;
  //const urlRequiresAuth = /^\/admin(\/|$)/.test(fullPath);
  const urlRequiresNonAuth = /^\/login(\/|$)/.test(fullPath);

  if (!userIsLoggedIn && !urlRequiresNonAuth) {
    return redirect("/login");
  }
  if (userIsLoggedIn && urlRequiresNonAuth) {
    return redirect("/");
  }
  return Promise.resolve();
}
```
Sorry for false alarm :) and thank you for very good example!
